name: menu_base
description: Used to create context or tray menus.
version: 0.2.0
homepage: https://github.com/leanflutter/menu_base

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
